name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build the Docker image
        #env : 
        #  DOCKER_USER : ${{secrets.DOCKERUSER}}
        #  DOCKER_PASSWORD : ${{secrets.DOCKERPSWD}}
        run: |
          docker build . --file ../Dockerfile --tag my-image-name:$(date +%d)
          docker tag my-image-name:$(date +%d) "${{ secrets.DOCKER_HUB_USERNAME }}/cigithub"
          docker push "${{ secrets.DOCKER_HUB_USERNAME }}/cigithub"

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
