name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env : 
        DOCKER_USER : ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD : ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker build . --file Dockerfile --tag my-image-name:$(date +%d)
        docker tag my-image-name:$(date +%d) "${DOCKER_USER}/cigithub"
        docker push "${DOCKER_USER}/cigithub"
