name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker task
        env: 
          DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}},
          DOCKER_PSW: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PSW
          docker build . --file Dokerfile --tag my-image-name:$(date +%d)
          docker tag my-image-name:$(date +%d) "${DOCKER_USER}/cigithub"
          docker push "${DOCKER_USER}/cigithub"
        
