name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        
      #-
      #  name: Login to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #    password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Docker task
        env: 
          DOCKER_USR: ${{secrets.DOCKER_HUB_USERNAME}},
          DOCKER_PSW: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USR --password-stdin $DOCKER_PSW
          docker build . --file Dokerfile --tag my-image-name:$(date +%d)
          docker tag my-image-name:$(date +%d) "${DOCKER_USR}/cigithub"
          docker push charlottemauvezin/cigithub:tagname
        
